set schema 'bilheteria';

CREATE TABLE FILME(
	CODIGO SERIAL PRIMARY KEY,
	TITULO VARCHAR(100) NOT NULL,
	SINOPSE TEXT,
	DURACAO_MIN INTEGER NOT NULL,
	CLASSIFICACAO VARCHAR(10)	
);

CREATE TABLE SALA(
NUMERO SERIAL,
QTD_POLTRONAS INTEGER,
PRIMARY KEY(NUMERO)
);

CREATE TABLE POLTRONA(
NUMERO_SALA INTEGER,
COD_POLTRONA VARCHAR(3)	
);

ALTER TABLE POLTRONA
ADD CONSTRAINT poltrona_pk
PRIMARY KEY(NUMERO_SALA,COD_POLTRONA);

ALTER TABLE POLTRONA
ADD CONSTRAINT poltrona_sala_fk
FOREIGN KEY(NUMERO_SALA) 
REFERENCES SALA(NUMERO);

INSERT INTO SALA(QTD_POLTRONAS)
VALUES(20);

CREATE TABLE SESSAO(
COD_SESSAO SERIAL PRIMARY KEY,
DT DATE,
HORARIO INTEGER,
DIM CHAR(2),
LINGUAGEM VARCHAR(20),
SALA_NUM INTEGER,
FILME_ID INTEGER,
FOREIGN KEY (SALA_NUM)  REFERENCES SALA(NUMERO),
FOREIGN KEY (FILME_ID)  REFERENCES FILME(CODIGO),
UNIQUE(DT,HORARIO,SALA_NUM)
);


SELECT * FROM SALA;

INSERT INTO POLTRONA VALUES
(1,'A1'), (1,'A2');

INSERT INTO POLTRONA VALUES
(3,'A1');
